import React, { createContext, useContext, useState, ReactNode } from 'react';

// Define translations inline first to avoid import issues
const thTranslations = {
  dashboard: {
    title: "แดชบอร์ด",
    subtitle: "ยินดีต้อนรับ จัดการระบบกิฟต์การ์ดของคุณ",
    totalCardsIssued: "การ์ดที่ออกทั้งหมด",
    activeCards: "การ์ดที่ใช้งานอยู่",
    outstandingFloat: "ยอดคงค้าง",
    redemptionRate: "อัตราการใช้งาน",
  },
  topup: {
    issuanceVsRedemption: "แนวโน้มการออกการ์ดเทียบกับการใช้งาน",
    channelBreakdown: "แยกตามช่องทาง",
    issued: "ออกการ์ด",
    redeemed: "ใช้งาน",
    corporatePortal: "พอร์ทัลองค์กร",
    retailPOS: "จุดขายปลีก",
    online: "ออนไลน์",
  },
  transactions: {
    title: "ฟีดธุรกรรมแบบเรียลไทม์",
    search: "ค้นหาธุรกรรม...",
    filter: "กรอง",
    cardId: "รหัสการ์ด",
    balance: "ยอดคงเหลือ",
    completed: "สำเร็จ",
    pending: "รอดำเนินการ",
    redemption: "การใช้งาน",
    topup: "เติมเงิน",
    partialRedemption: "การใช้งานบางส่วน",
    refund: "คืนเงิน",
    managementTitle: "จัดการธุรกรรม",
    managementSubtitle: "ติดตามและจัดการธุรกรรมการ์ดทั้งหมด",
    export: "ส่งออก",
    refresh: "รีเฟรช",
    totalTransactions: "ธุรกรรมทั้งหมด",
    successful: "สำเร็จ",
    failed: "ล้มเหลว",
    realTimeFeed: "ฟีดธุรกรรมแบบเรียลไทม์",
    realTimeFeedDesc: "การติดตามธุรกรรมสดพร้อมตัวกรองขั้นสูง",
    allStatus: "ทุกสถานะ",
    allTypes: "ทุกประเภท",
    purchase: "ซื้อ",
    partialRedemptionTitle: "การใช้งานบางส่วน",
    partialRedemptionDesc: "จัดการการใช้งานการ์ดบางส่วนและยอดคงเหลือ",
    partialRedemptionRules: "กฎการใช้งานบางส่วน",
    active: "ใช้งานอยู่",
    minimumBalance: "ยอดคงเหลือขั้นต่ำที่ต้องการ",
    allowPartialRedemptions: "อนุญาตการใช้งานบางส่วน",
    yes: "ใช่",
    minimumTransactionAmount: "จำนวนธุรกรรมขั้นต่ำ",
    configureRules: "กำหนดค่ากฎ",
    disputeHandling: "การจัดการข้อพิพาท",
    disputeHandlingDesc: "จัดการข้อพิพาทธุรกรรมและการคืนเงิน",
    transaction: "ธุรกรรม",
    amount: "จำนวน",
    reason: "เหตุผล",
    resolved: "แก้ไขแล้ว",
    investigating: "กำลังตรวจสอบ",
    reversalRefundCenter: "ศูนย์การยกเลิกและคืนเงิน",
    reversalRefundCenterDesc: "ดำเนินการยกเลิกธุรกรรมและการคืนเงิน",
    pendingReversals: "การยกเลิกที่รอดำเนินการ",
    completedRefunds: "การคืนเงินที่เสร็จสิ้น",
    failedReversals: "การยกเลิกที่ล้มเหลว",
    process: "ดำเนินการ",
    view: "ดู",
    retry: "ลองใหม่",
  },
  account: {
    title: "จัดการบัญชีและบทบาท",
    subtitle: "จัดการบทบาทผู้ใช้ สิทธิ์ และการควบคุมการเข้าถึง",
    addUser: "เพิ่มผู้ใช้",
    users: "ผู้ใช้",
    permissions: "สิทธิ์",
    roleHierarchy: "ลำดับชั้นบทบาท",
    roleHierarchyDesc: "ดูและจัดการโครงสร้างสิทธิ์บทบาท",
    recentActivity: "กิจกรรมล่าสุด",
    recentActivityDesc: "บันทึกการตรวจสอบของการดำเนินการระบบล่าสุด",
    ssoIntegration: "การรวม SSO",
    ssoIntegrationDesc: "กำหนดค่าผู้ให้บริการลงชื่อเข้าใช้เดียว",
    fullAccess: "เข้าถึงได้เต็มรูปแบบ",
    settlementReports: "การชำระเงิน รายงาน",
    merchantOperations: "การดำเนินการร้านค้า",
    customerSupport: "การสนับสนุนลูกค้า",
    fullSystemAccess: "เข้าถึงระบบเต็มรูปแบบ",
    configure: "กำหนดค่า",
    setup: "ตั้งค่า",
    active: "ใช้งานอยู่",
    inactive: "ไม่ใช้งาน",
    oauth: "การรวม OAuth 2.0",
    activeDirectory: "การซิงค์ Active Directory",
    enterpriseSSO: "Enterprise SSO",
    createdMerchant: "สร้างบัญชีร้านค้า",
    updatedSettlement: "อัปเดตกฎการชำระเงิน",
    deletedCards: "ลบการ์ดที่หมดอายุ",
    minAgo: "นาทีที่แล้ว",
    hourAgo: "ชั่วโมงที่แล้ว",
  },
  cardInventory: {
    title: "จัดการการ์ดและสินค้าคงคลัง",
    subtitle: "จัดการการออกการ์ด สินค้าคงคลัง และวงจรชีวิต",
    bulkUpload: "อัปโหลดจำนวนมาก",
    newBatch: "ชุดใหม่",
    totalCardsIssued: "การ์ดที่ออกทั้งหมด",
    activeCards: "การ์ดที่ใช้งานอยู่",
    expiredCards: "การ์ดที่หมดอายุ",
    pendingActivation: "รอการเปิดใช้งาน",
    corporateGeneration: "การสร้างการ์ดองค์กร",
    corporateGenerationDesc: "สร้างและจัดการชุดการ์ดองค์กร",
    campaignName: "ชื่อแคมเปญ",
    enterCampaignName: "ป้อนชื่อแคมเปญ",
    batchAmount: "จำนวนชุด",
    cardValue: "มูลค่าการ์ด",
    whitelistUpload: "อัปโหลดรายชื่อที่อนุญาต",
    dropCsvFile: "วางไฟล์ CSV ที่นี่หรือคลิกเพื่อเรียกดู",
    generateBatch: "สร้างชุด",
    recentBatches: "ชุดล่าสุด",
    recentBatchesDesc: "ติดตามความคืบหน้าการสร้างชุด",
    cards: "การ์ด",
    completed: "เสร็จสิ้น",
    processing: "กำลังดำเนินการ",
    pending: "รอดำเนินการ",
    cardTypeDistribution: "การกระจายประเภทการ์ด",
    cardTypeDistributionDesc: "ภาพรวมของประเภทการ์ดและสถานะ",
    physicalCards: "การ์ดจริง",
    eGiftCards: "การ์ดของขวัญดิจิทัล",
    corporateCards: "การ์ดองค์กร",
    total: "รวม",
    active: "ใช้งานอยู่",
    expired: "หมดอายุ",
    topUpReloadControls: "การควบคุมการเติมเงินและรีโหลด",
    topUpReloadControlsDesc: "จัดการการรีโหลดการ์ดและการตั้งค่าการเติมเงิน",
    autoTopUp: "การเติมเงินอัตโนมัติ",
    autoTopUpDesc: "การรีโหลดยอดเงินอัตโนมัติ",
    manualReload: "รีโหลดด้วยตนเอง",
    manualReloadDesc: "การเติมเงินที่ผู้ใช้เริ่มต้น",
    corporateReload: "รีโหลดองค์กร",
    corporateReloadDesc: "การเติมเงินองค์กรจำนวนมาก",
    enabled: "เปิดใช้งาน",
    expiryManagement: "การจัดการการหมดอายุ",
    expiryManagementDesc: "การตั้งค่าการหมดอายุและการเรียกคืนการ์ด",
    expiringSoon: "ใกล้หมดอายุ",
    expiredToday: "หมดอายุวันนี้",
    sendExpiryNotifications: "ส่งการแจ้งเตือนการหมดอายุ",
    recallExpiredCards: "เรียกคืนการ์ดที่หมดอายุ",
  },
  common: {
    language: "ภาษา",
    thai: "ไทย",
    english: "อังกฤษ",
  }
};

const enTranslations = {
  dashboard: {
    title: "Dashboard",
    subtitle: "Welcome back, manage your gift card system",
    totalCardsIssued: "Total Cards Issued",
    activeCards: "Active Cards",
    outstandingFloat: "Outstanding Float",
    redemptionRate: "Redemption Rate",
  },
  topup: {
    issuanceVsRedemption: "Issuance vs Redemption Trend",
    channelBreakdown: "Channel Breakdown",
    issued: "Issued",
    redeemed: "Redeemed",
    corporatePortal: "Corporate Portal",
    retailPOS: "Retail POS", 
    online: "Online",
  },
  transactions: {
    title: "Real-time Transaction Feed",
    search: "Search transactions...",
    filter: "Filter",
    cardId: "Card ID",
    balance: "Balance",
    completed: "completed",
    pending: "pending",
    redemption: "redemption",
    topup: "topup",
    partialRedemption: "partial redemption",
    refund: "refund",
    managementTitle: "Transaction Management",
    managementSubtitle: "Monitor and manage all card transactions",
    export: "Export",
    refresh: "Refresh",
    totalTransactions: "Total Transactions",
    successful: "Successful",
    failed: "Failed",
    realTimeFeed: "Real-Time Transaction Feed",
    realTimeFeedDesc: "Live transaction monitoring with advanced filters",
    allStatus: "All Status",
    allTypes: "All Types",
    purchase: "Purchase",
    partialRedemptionTitle: "Partial Redemption",
    partialRedemptionDesc: "Manage partial card redemptions and balances",
    partialRedemptionRules: "Partial Redemption Rules",
    active: "Active",
    minimumBalance: "Minimum balance required",
    allowPartialRedemptions: "Allow partial redemptions",
    yes: "Yes",
    minimumTransactionAmount: "Minimum transaction amount",
    configureRules: "Configure Rules",
    disputeHandling: "Dispute Handling",
    disputeHandlingDesc: "Manage transaction disputes and refunds",
    transaction: "Transaction",
    amount: "Amount",
    reason: "Reason",
    resolved: "resolved",
    investigating: "investigating",
    reversalRefundCenter: "Reversal & Refund Center",
    reversalRefundCenterDesc: "Process transaction reversals and refunds",
    pendingReversals: "Pending Reversals",
    completedRefunds: "Completed Refunds",
    failedReversals: "Failed Reversals",
    process: "Process",
    view: "View",
    retry: "Retry",
  },
  account: {
    title: "Account & Role Management",
    subtitle: "Manage user roles, permissions, and access control",
    addUser: "Add User",
    users: "users",
    permissions: "permissions",
    roleHierarchy: "Role Hierarchy",
    roleHierarchyDesc: "View and manage role permissions structure",
    recentActivity: "Recent Activity",
    recentActivityDesc: "Audit trail of recent system actions",
    ssoIntegration: "SSO Integration",
    ssoIntegrationDesc: "Configure single sign-on providers",
    fullAccess: "Full Access",
    settlementReports: "Settlement, Reports",
    merchantOperations: "Merchant Operations",
    customerSupport: "Customer Support",
    fullSystemAccess: "Full system access",
    configure: "Configure",
    setup: "Setup",
    active: "Active",
    inactive: "Inactive",
    oauth: "OAuth 2.0 integration",
    activeDirectory: "Active Directory sync",
    enterpriseSSO: "Enterprise SSO",
    createdMerchant: "Created merchant account",
    updatedSettlement: "Updated settlement rules",
    deletedCards: "Deleted expired cards",
    minAgo: "min ago",
    hourAgo: "hour ago",
  },
  cardInventory: {
    title: "Card & Inventory Management",
    subtitle: "Manage card issuance, inventory, and lifecycle",
    bulkUpload: "Bulk Upload",
    newBatch: "New Batch",
    totalCardsIssued: "Total Cards Issued",
    activeCards: "Active Cards",
    expiredCards: "Expired Cards",
    pendingActivation: "Pending Activation",
    corporateGeneration: "Corporate Generation",
    corporateGenerationDesc: "Create and manage corporate card batches",
    campaignName: "Campaign Name",
    enterCampaignName: "Enter campaign name",
    batchAmount: "Batch Amount",
    cardValue: "Card Value",
    whitelistUpload: "Whitelist Upload",
    dropCsvFile: "Drop CSV file here or click to browse",
    generateBatch: "Generate Batch",
    recentBatches: "Recent Batches",
    recentBatchesDesc: "Track batch generation progress",
    cards: "cards",
    completed: "completed",
    processing: "processing",
    pending: "pending",
    cardTypeDistribution: "Card Type Distribution",
    cardTypeDistributionDesc: "Overview of card types and their status",
    physicalCards: "Physical Cards",
    eGiftCards: "E-Gift Cards",
    corporateCards: "Corporate Cards",
    total: "total",
    active: "Active",
    expired: "Expired",
    topUpReloadControls: "Top-Up & Reload Controls",
    topUpReloadControlsDesc: "Manage card reloading and top-up settings",
    autoTopUp: "Auto Top-Up",
    autoTopUpDesc: "Automatic balance reload",
    manualReload: "Manual Reload",
    manualReloadDesc: "User-initiated top-ups",
    corporateReload: "Corporate Reload",
    corporateReloadDesc: "Bulk corporate top-ups",
    enabled: "Enabled",
    expiryManagement: "Expiry Management",
    expiryManagementDesc: "Card expiration and recall settings",
    expiringSoon: "Expiring Soon",
    expiredToday: "Expired Today",
    sendExpiryNotifications: "Send Expiry Notifications",
    recallExpiredCards: "Recall Expired Cards",
  },
  common: {
    language: "Language",
    thai: "Thai",
    english: "English",
  }
};

type Language = 'th' | 'en';
type Translations = typeof thTranslations;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('th');

  const translations = {
    th: thTranslations,
    en: enTranslations,
  };

  const value = {
    language,
    setLanguage,
    t: translations[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // Provide a fallback instead of throwing
    console.warn('useLanguage called outside of LanguageProvider, using fallback');
    return {
      language: 'th' as Language,
      setLanguage: () => {},
      t: thTranslations,
    };
  }
  return context;
}