import React, { createContext, useContext, useState, ReactNode } from 'react';

// Define translations inline first to avoid import issues
const thTranslations = {
  dashboard: {
    title: "แดชบอร์ด",
    subtitle: "ยินดีต้อนรับ จัดการระบบกิฟต์การ์ดของคุณ",
    totalCardsIssued: "การ์ดที่ออกทั้งหมด",
    activeCards: "การ์ดที่ใช้งานอยู่",
    outstandingFloat: "ยอดคงค้าง",
    redemptionRate: "อัตราการใช้งาน",
  },
  topup: {
    issuanceVsRedemption: "แนวโน้มการออกการ์ดเทียบกับการใช้งาน",
    channelBreakdown: "แยกตามช่องทาง",
    issued: "ออกการ์ด",
    redeemed: "ใช้งาน",
    corporatePortal: "พอร์ทัลองค์กร",
    retailPOS: "จุดขายปลีก",
    online: "ออนไลน์",
  },
  transactions: {
    title: "ฟีดธุรกรรมแบบเรียลไทม์",
    search: "ค้นหาธุรกรรม...",
    filter: "กรอง",
    cardId: "รหัสการ์ด",
    balance: "ยอดคงเหลือ",
    completed: "สำเร็จ",
    pending: "รอดำเนินการ",
    redemption: "การใช้งาน",
    topup: "เติมเงิน",
    partialRedemption: "การใช้งานบางส่วน",
    refund: "คืนเงิน",
    managementTitle: "จัดการธุรกรรม",
    managementSubtitle: "ติดตามและจัดการธุรกรรมการ์ดทั้งหมด",
    export: "ส่งออก",
    refresh: "รีเฟรช",
    totalTransactions: "ธุรกรรมทั้งหมด",
    successful: "สำเร็จ",
    failed: "ล้มเหลว",
    realTimeFeed: "ฟีดธุรกรรมแบบเรียลไทม์",
    realTimeFeedDesc: "การติดตามธุรกรรมสดพร้อมตัวกรองขั้นสูง",
    allStatus: "ทุกสถานะ",
    allTypes: "ทุกประเภท",
    purchase: "ซื้อ",
    partialRedemptionTitle: "การใช้งานบางส่วน",
    partialRedemptionDesc: "จัดการการใช้งานการ์ดบางส่วนและยอดคงเหลือ",
    partialRedemptionRules: "กฎการใช้งานบางส่วน",
    active: "ใช้งานอยู่",
    minimumBalance: "ยอดคงเหลือขั้นต่ำที่ต้องการ",
    allowPartialRedemptions: "อนุญาตการใช้งานบางส่วน",
    yes: "ใช่",
    minimumTransactionAmount: "จำนวนธุรกรรมขั้นต่ำ",
    configureRules: "กำหนดค่ากฎ",
    disputeHandling: "การจัดการข้อพิพาท",
    disputeHandlingDesc: "จัดการข้อพิพาทธุรกรรมและการคืนเงิน",
    transaction: "ธุรกรรม",
    amount: "จำนวน",
    reason: "เหตุผล",
    resolved: "แก้ไขแล้ว",
    investigating: "กำลังตรวจสอบ",
    reversalRefundCenter: "ศูนย์การยกเลิกและคืนเงิน",
    reversalRefundCenterDesc: "ดำเนินการยกเลิกธุรกรรมและการคืนเงิน",
    pendingReversals: "การยกเลิกที่รอดำเนินการ",
    completedRefunds: "การคืนเงินที่เสร็จสิ้น",
    failedReversals: "การยกเลิกที่ล้มเหลว",
    process: "ดำเนินการ",
    view: "ดู",
    retry: "ลองใหม่",
  },
  account: {
    title: "จัดการบัญชีและบทบาท",
    subtitle: "จัดการบทบาทผู้ใช้ สิทธิ์ และการควบคุมการเข้าถึง",
    addUser: "เพิ่มผู้ใช้",
    users: "ผู้ใช้",
    permissions: "สิทธิ์",
    roleHierarchy: "ลำดับชั้นบทบาท",
    roleHierarchyDesc: "ดูและจัดการโครงสร้างสิทธิ์บทบาท",
    recentActivity: "กิจกรรมล่าสุด",
    recentActivityDesc: "บันทึกการตรวจสอบของการดำเนินการระบบล่าสุด",
    ssoIntegration: "การรวม SSO",
    ssoIntegrationDesc: "กำหนดค่าผู้ให้บริการลงชื่อเข้าใช้เดียว",
    fullAccess: "เข้าถึงได้เต็มรูปแบบ",
    settlementReports: "การชำระเงิน รายงาน",
    merchantOperations: "การดำเนินการร้านค้า",
    customerSupport: "การสนับสนุนลูกค้า",
    fullSystemAccess: "เข้าถึงระบบเต็มรูปแบบ",
    configure: "กำหนดค่า",
    setup: "ตั้งค่า",
    active: "ใช้งานอยู่",
    inactive: "ไม่ใช้งาน",
    oauth: "การรวม OAuth 2.0",
    activeDirectory: "การซิงค์ Active Directory",
    enterpriseSSO: "Enterprise SSO",
    createdMerchant: "สร้างบัญชีร้านค้า",
    updatedSettlement: "อัปเดตกฎการชำระเงิน",
    deletedCards: "ลบการ์ดที่หมดอายุ",
    minAgo: "นาทีที่แล้ว",
    hourAgo: "ชั่วโมงที่แล้ว",
  },
  cardInventory: {
    title: "จัดการการ์ดและสินค้าคงคลัง",
    subtitle: "จัดการการออกการ์ด สินค้าคงคลัง และวงจรชีวิต",
    bulkUpload: "อัปโหลดจำนวนมาก",
    newBatch: "ชุดใหม่",
    totalCardsIssued: "การ์ดที่ออกทั้งหมด",
    activeCards: "การ์ดที่ใช้งานอยู่",
    expiredCards: "การ์ดที่หมดอายุ",
    pendingActivation: "รอการเปิดใช้งาน",
    corporateGeneration: "การสร้างการ์ดองค์กร",
    corporateGenerationDesc: "สร้างและจัดการชุดการ์ดองค์กร",
    campaignName: "ชื่อแคมเปญ",
    enterCampaignName: "ป้อนชื่อแคมเปญ",
    batchAmount: "จำนวนชุด",
    cardValue: "มูลค่าการ์ด",
    whitelistUpload: "อัปโหลดรายชื่อที่อนุญาต",
    dropCsvFile: "วางไฟล์ CSV ที่นี่หรือคลิกเพื่อเรียกดู",
    generateBatch: "สร้างชุด",
    recentBatches: "ชุดล่าสุด",
    recentBatchesDesc: "ติดตามความคืบหน้าการสร้างชุด",
    cards: "การ์ด",
    completed: "เสร็จสิ้น",
    processing: "กำลังดำเนินการ",
    pending: "รอดำเนินการ",
    cardTypeDistribution: "การกระจายประเภทการ์ด",
    cardTypeDistributionDesc: "ภาพรวมของประเภทการ์ดและสถานะ",
    physicalCards: "การ์ดจริง",
    eGiftCards: "การ์ดของขวัญดิจิทัล",
    corporateCards: "การ์ดองค์กร",
    total: "รวม",
    active: "ใช้งานอยู่",
    expired: "หมดอายุ",
    topUpReloadControls: "การควบคุมการเติมเงินและรีโหลด",
    topUpReloadControlsDesc: "จัดการการรีโหลดการ์ดและการตั้งค่าการเติมเงิน",
    autoTopUp: "การเติมเงินอัตโนมัติ",
    autoTopUpDesc: "การรีโหลดยอดเงินอัตโนมัติ",
    manualReload: "รีโหลดด้วยตนเอง",
    manualReloadDesc: "การเติมเงินที่ผู้ใช้เริ่มต้น",
    corporateReload: "รีโหลดองค์กร",
    corporateReloadDesc: "การเติมเงินองค์กรจำนวนมาก",
    enabled: "เปิดใช้งาน",
    expiryManagement: "การจัดการการหมดอายุ",
    expiryManagementDesc: "การตั้งค่าการหมดอายุและการเรียกคืนการ์ด",
    expiringSoon: "ใกล้หมดอายุ",
    expiredToday: "หมดอายุวันนี้",
    sendExpiryNotifications: "ส่งการแจ้งเตือนการหมดอายุ",
    recallExpiredCards: "เรียกคืนการ์ดที่หมดอายุ",
  },
  merchant: {
    title: "จัดการร้านค้าและผู้เช่า",
    subtitle: "จัดการการขึ้นทะเบียนร้านค้า แดชบอร์ด และการชำระเงิน",
    viewAll: "ดูทั้งหมด",
    addMerchant: "เพิ่มร้านค้า",
    totalMerchants: "ร้านค้าทั้งหมด",
    activeMerchants: "ร้านค้าที่ใช้งานอยู่",
    pendingApproval: "รออนุมัติ",
    inactive: "ไม่ใช้งาน",
    merchantOnboarding: "การขึ้นทะเบียนร้านค้า",
    merchantOnboardingDesc: "แบบฟอร์มการขึ้นทะเบียนด่วนสำหรับร้านค้าใหม่",
    businessName: "ชื่อธุรกิจ",
    enterBusinessName: "ป้อนชื่อธุรกิจ",
    category: "หมวดหมู่",
    foodBeverage: "อาหารและเครื่องดื่ม",
    contactEmail: "อีเมลติดต่อ",
    businessAddress: "ที่อยู่ธุรกิจ",
    feeStructure: "โครงสร้างค่าธรรมเนียม",
    transactionPercent: "เปอร์เซ็นต์ธุรกรรม",
    monthlyFee: "ค่าธรรมเนียมรายเดือน",
    submitApplication: "ส่งใบสมัคร",
    pendingApprovals: "รออนุมัติ",
    pendingApprovalsDesc: "ร้านค้าที่รออนุมัติ",
    complete: "สมบูรณ์",
    pending: "รอดำเนินการ",
    electronics: "อิเล็กทรอนิกส์",
    retail: "ขายปลีก",
    submitted: "ส่งแล้ว",
    review: "ตรวจสอบ",
    approve: "อนุมัติ",
    topPerformingMerchants: "ร้านค้าที่มีผลงานดี",
    topPerformingMerchantsDesc: "แดชบอร์ดผลงานและการวิเคราะห์ร้านค้า",
    transactions: "ธุรกรรม",
    revenue: "รายได้",
    growth: "การเติบโต",
    active: "ใช้งานอยู่",
    edit: "แก้ไข",
    feeStructureManagement: "การจัดการโครงสร้างค่าธรรมเนียม",
    feeStructureManagementDesc: "กำหนดค่าโครงสร้างค่าธรรมเนียมร้านค้า",
    standardFeeStructure: "โครงสร้างค่าธรรมเนียมมาตรฐาน",
    transactionFee: "ค่าธรรมเนียมธุรกรรม",
    setupFee: "ค่าธรรมเนียมการตั้งค่า",
    premiumFeeStructure: "โครงสร้างค่าธรรมเนียมพรีเมียม",
    editFeeStructures: "แก้ไขโครงสร้างค่าธรรมเนียม",
    settlementCycles: "รอบการชำระเงิน",
    settlementCyclesDesc: "จัดการตารางการชำระเงินร้านค้า",
    scheduled: "กำหนดแล้ว",
    processing: "กำลังดำเนินการ",
    amount: "จำนวน",
    cycle: "รอบ",
    nextSettlement: "การชำระครั้งถัดไป",
    daily: "รายวัน",
    weekly: "รายสัปดาห์",
    biweekly: "ทุกสองสัปดาห์",
    configureSchedules: "กำหนดค่าตารางเวลา",
  },
  settlement: {
    title: "การชำระเงินและการกระทบยอด",
    subtitle: "จัดการการกระทบยอดอัตโนมัติและการจัดการเงินทุน",
    exportReport: "ส่งออกรายงาน",
    reconcileNow: "กระทบยอดทันที",
    totalFloat: "เงินทุนรวม",
    pendingSettlements: "การชำระเงินที่รอดำเนินการ",
    reconciledToday: "กระทบยอดวันนี้",
    exceptions: "ข้อยกเว้น",
    automatedReconciliation: "การกระทบยอดอัตโนมัติ",
    automatedReconciliationDesc: "สถานะการกระทบยอดแบบเรียลไทม์สำหรับร้านค้าทั้งหมด",
    last: "ครั้งล่าสุด",
    next: "ครั้งถัดไป",
    completed: "เสร็จสิ้น",
    running: "กำลังทำงาน",
    pending: "รอดำเนินการ",
    failed: "ล้มเหลว",
    floatManagement: "การจัดการเงินทุน",
    floatManagementDesc: "ติดตามและจัดการยอดเงินทุนของระบบ",
    currentFloatBalance: "ยอดเงินทุนปัจจุบัน",
    ofTarget: "ของเป้าหมาย",
    target: "เป้าหมาย",
    floatMovements: "การเคลื่อนไหวของเงินทุน",
    cardIssuance: "การออกการ์ด",
    merchantSettlement: "การชำระเงินร้านค้า",
    cardTopUp: "การเติมเงินการ์ด",
    refundProcessing: "การดำเนินการคืนเงิน",
    settlementFileExport: "การส่งออกไฟล์การชำระเงิน",
    settlementFileExportDesc: "สร้างและดาวน์โหลดรายงานการชำระเงิน",
    dailySettlement: "การชำระเงินรายวัน",
    dailySettlementDesc: "ส่งออกสรุปการชำระเงินรายวัน",
    generateReport: "สร้างรายงาน",
    lastGenerated: "สร้างครั้งล่าสุด",
    monthlyReconciliation: "การกระทบยอดรายเดือน",
    monthlyReconciliationDesc: "รายงานการกระทบยอดรายเดือน",
    exceptionReport: "รายงานข้อยกเว้น",
    exceptionReportDesc: "รายละเอียดการกระทบยอดที่ล้มเหลว",
    hoursAgo: "ชั่วโมงที่แล้ว",
    dayAgo: "วันที่แล้ว",
    manual: "ด้วยตนเอง",
  },
  common: {
    language: "ภาษา",
    thai: "ไทย",
    english: "อังกฤษ",
  },
  compliance: {
    title: 'การปฏิบัติตามกฎระเบียบและการตรวจสอบ',
    subtitle: 'การปฏิบัติตามกฎระเบียบ การเก็บรักษาข้อมูล และการจัดการการตรวจสอบ',
    complianceScore: 'คะแนนการปฏิบัติตามกฎระเบียบ',
    activePolicies: 'นโยบายที่ใช้งาน',
    pendingReviews: 'รอการตรวจสอบ',
    violations: 'การละเมิด',
    exportReport: 'ส่งออกรายงาน',
    generateAudit: 'สร้างการตรวจสอบ',
    regulatoryReporting: {
      title: 'การรายงานตามกฎระเบียบ',
      subtitle: 'ติดตามสถานะการปฏิบัติตามกฎระเบียบและสร้างรายงานตามกฎระเบียบ',
      lastAudit: 'ตรวจสอบล่าสุด',
      nextDue: 'ครบกำหนดถัดไป',
      highPriority: 'ลำดับความสำคัญสูง',
      mediumPriority: 'ลำดับความสำคัญปานกลาง',
      compliant: 'ปฏิบัติตาม',
      pending: 'รอดำเนินการ',
      view: 'ดู'
    },
    dataRetention: {
      title: 'นโยบายการเก็บรักษาข้อมูล',
      subtitle: 'จัดการวงจรชีวิตข้อมูลและกฎการเก็บรักษา',
      autoDelete: 'ลบอัตโนมัติ',
      manual: 'ลบด้วยตนเอง',
      retentionPeriod: 'ระยะเวลาการเก็บรักษา',
      lastCleanup: 'ทำความสะอาดล่าสุด',
      configurePolicies: 'กำหนดค่านโยบาย',
      transactionRecords: 'บันทึกธุรกรรม',
      customerData: 'ข้อมูลลูกค้า',
      auditLogs: 'บันทึกการตรวจสอบ',
      financialReports: 'รายงานทางการเงิน',
      years: 'ปี'
    },
    consentManagement: {
      title: 'การจัดการความยินยอม',
      subtitle: 'ติดตามและจัดการการตั้งค่าความยินยอมของผู้ใช้',
      total: 'รวม',
      consented: 'ยินยอม',
      declined: 'ปฏิเสธ',
      pending: 'รอดำเนินการ',
      manageConsent: 'จัดการความยินยอม',
      marketingCommunications: 'การสื่อสารการตลาด',
      dataProcessing: 'การประมวลผลข้อมูล',
      thirdPartySharing: 'การแบ่งปันข้อมูลกับบุคคลที่สาม'
    },
    auditTrail: {
      title: 'บันทึกการตรวจสอบ',
      subtitle: 'บันทึกการตรวจสอบที่ครอบคลุมและการติดตามกิจกรรม',
      systemEventsToday: 'เหตุการณ์ระบบวันนี้',
      auditCoverage: 'ความครอบคลุมการตรวจสอบ',
      securityAlerts: 'การแจ้งเตือนความปลอดภัย',
      viewFullAuditLog: 'ดูบันทึกการตรวจสอบทั้งหมด',
      exportAuditReport: 'ส่งออกรายงานการตรวจสอบ'
    }
  },
  security: {
    title: 'ความปลอดภัยและการปฏิบัติตามกฎระเบียบ',
    subtitle: 'จัดการการเข้าถึงของผู้ใช้ บันทึกการตรวจสอบ การตรวจจับการฉ้อโกง และเครื่องมือการปฏิบัติตามกฎระเบียบ',
    fraudDetectionRate: 'อัตราการตรวจจับการฉ้อโกง',
    blockedTransactions: 'ธุรกรรมที่ถูกบล็อก',
    mfaCoverage: 'ความครอบคลุม MFA',
    securityAlerts: 'การแจ้งเตือนความปลอดภัย',
    viewLogs: 'ดูบันทึก',
    configureRules: 'กำหนดค่ากฎ',
    userAccessControl: 'การควบคุมการเข้าถึงผู้ใช้',
    auditTrail: 'บันทึกการตรวจสอบ',
    amlReporting: 'การรายงาน AML',
    pdpaCompliance: 'การปฏิบัติตาม PDPA',
    userManagement: {
      title: 'การจัดการผู้ใช้',
      subtitle: 'สร้างและจัดการบัญชีผู้ใช้ด้วยสิทธิ์ตามบทบาท',
      addUser: 'เพิ่มผู้ใช้',
      exportUsers: 'ส่งออกผู้ใช้',
      viewAllUsers: 'ดูผู้ใช้ทั้งหมด',
      active: 'ใช้งานอยู่',
      inactive: 'ไม่ใช้งาน'
    },
    rolePermissions: {
      title: 'สิทธิ์ตามบทบาท',
      subtitle: 'จัดการบทบาทและเทมเพลตสิทธิ์',
      createRole: 'สร้างบทบาท',
      permissionMatrix: 'เมทริกซ์สิทธิ์',
      systemAdmin: 'ผู้ดูแลระบบ',
      financeManager: 'ผู้จัดการการเงิน',
      supportAgent: 'เจ้าหน้าที่สนับสนุน',
      merchantManager: 'ผู้จัดการร้านค้า',
      fullAccess: 'เข้าถึงเต็มรูปแบบ',
      financialOperations: 'การดำเนินการทางการเงิน',
      customerSupport: 'การสนับสนุนลูกค้า',
      tenantManagement: 'การจัดการผู้เช่า',
      completeSystemAccess: 'เข้าถึงระบบอย่างสมบูรณ์',
      settlementReconciliation: 'การชำระเงินและการกระทบยอด',
      cardInquiryAssistance: 'การสอบถามการ์ดและความช่วยเหลือ',
      merchantOperations: 'การดำเนินการร้านค้า',
      users: 'ผู้ใช้'
    },
    authentication: {
      title: 'การตั้งค่าการรับรองตัวตน',
      subtitle: 'การกำหนดค่าการรับรองตัวตนหลายปัจจัยและ SSO',
      multiFactorAuth: 'การรับรองตัวตนหลายปัจจัย',
      smsAuth: 'การรับรองตัวตนผ่าน SMS',
      emailVerification: 'การยืนยันทางอีเมล',
      authenticatorApp: 'แอปรับรองตัวตน',
      hardwareToken: 'โทเค็นฮาร์ดแวร์',
      textMessageVerification: 'การยืนยันข้อความ',
      emailBasedAuth: 'การรับรองตัวตนทางอีเมล',
      totpAppVerification: 'การยืนยันแอป TOTP',
      physicalSecurityKeys: 'กุญแจความปลอดภัยทางกายภาพ',
      ssoIntegration: 'การรวม SSO',
      googleSSO: 'Google SSO',
      microsoftSSO: 'Microsoft SSO',
      gmailAuth: 'การรับรองตัวตนผ่าน Gmail',
      azureAdIntegration: 'การรวมกับ Azure AD'
    },
    activityLogging: {
      title: 'การบันทึกกิจกรรม',
      subtitle: 'บันทึกการตรวจสอบแบบเรียลไทม์ของกิจกรรมระบบทั้งหมด',
      search: 'ค้นหา',
      filter: 'กรอง',
      export: 'ส่งออก',
      timestamp: 'เวลา',
      user: 'ผู้ใช้',
      action: 'การดำเนินการ',
      module: 'โมดูล'
    },
    logManagement: {
      title: 'การจัดการบันทึก',
      subtitle: 'กำหนดค่าการเก็บรักษาและการเก็บถาวรบันทึก',
      retentionPeriod: 'ระยะเวลาการเก็บรักษาบันทึก',
      autoArchival: 'การเก็บถาวรอัตโนมัติ',
      days90: '90 วัน',
      days180: '180 วัน',
      year1: '1 ปี',
      years3: '3 ปี',
      enabled: 'เปิดใช้งาน',
      disabled: 'ปิดใช้งาน'
    }
  },
  integration: {
    title: 'การรวมระบบและการจัดการ API',
    subtitle: 'จัดการจุดปลาย API เว็บฮุก และการรวมระบบภายนอก',
    totalApiCalls: 'จำนวน API Calls ทั้งหมด',
    successRate: 'อัตราความสำเร็จ',
    avgResponseTime: 'เวลาตอบสนองเฉลี่ย',
    rateLimitHits: 'จำนวนการเข้าถึงขีดจำกัด',
    viewDocs: 'ดูเอกสาร',
    apiConsole: 'API Console',
    apiCatalogSandbox: {
      title: 'API Catalog และ Sandbox',
      subtitle: 'จัดการจุดปลาย API และทดสอบในสภาพแวดล้อม sandbox',
      cardIssuance: 'การออกการ์ด',
      transactionProcessing: 'การประมวลผลธุรกรรม',
      balanceInquiry: 'การสอบถามยอดเงิน',
      merchantVerification: 'การยืนยันร้านค้า',
      uptime: 'uptime',
      calls: 'calls',
      rateLimit: 'ขีดจำกัดอัตรา',
      test: 'ทดสอบ',
      openSandbox: 'เปิด Sandbox'
    },
    apiStatusDashboard: {
      title: 'แดชบอร์ดสถานะ API',
      subtitle: 'ติดตามการรวมระบบภายนอก',
      crmSystem: 'ระบบ CRM',
      paymentGateway: 'เกตเวย์การชำระเงิน',
      merchantDirectory: 'ไดเรกทอรีร้านค้า',
      notificationService: 'บริการแจ้งเตือน',
      active: 'ใช้งานอยู่',
      inactive: 'ไม่ใช้งาน',
      lastHeartbeat: 'Heartbeat ล่าสุด',
      errorRate: 'อัตราข้อผิดพลาด',
      retryCount: 'จำนวนการลองใหม่',
      minAgo: 'นาทีที่แล้ว',
      secAgo: 'วินาทีที่แล้ว'
    },
    webhookManagement: {
      title: 'การจัดการ Webhook',
      subtitle: 'กำหนดค่าและจัดการจุดปลาย webhook',
      transactionCompleted: 'ธุรกรรมสำเร็จ',
      cardIssued: 'การ์ดถูกออก',
      balanceUpdated: 'ยอดเงินอัปเดต',
      merchantOnboarded: 'ร้านค้าขึ้นทะเบียน',
      lastTrigger: 'ทริกเกอร์ล่าสุด',
      edit: 'แก้ไข',
      addWebhook: 'เพิ่ม Webhook',
      hourAgo: 'ชั่วโมงที่แล้ว',
      dayAgo: 'วันที่แล้ว'
    },
    rateLimiting: {
      title: 'การจำกัดอัตรา',
      subtitle: 'กำหนดค่าขีดจำกัดและโควต้า API',
      currentUsage: 'การใช้งานปัจจุบัน',
      apiCallsPerMinute: 'API Calls (ต่อนาที)',
      concurrentConnections: 'การเชื่อมต่อพร้อมกัน',
      webhookDeliveries: 'การส่ง Webhook',
      rateLimitConfig: 'การกำหนดค่าขีดจำกัดอัตรา',
      requestsPerMinute: 'คำขอต่อนาที',
      burstLimit: 'ขีดจำกัด Burst',
      updateLimits: 'อัปเดตขีดจำกัด'
    }
  }
};

const enTranslations = {
  dashboard: {
    title: "Dashboard",
    subtitle: "Welcome back, manage your gift card system",
    totalCardsIssued: "Total Cards Issued",
    activeCards: "Active Cards",
    outstandingFloat: "Outstanding Float",
    redemptionRate: "Redemption Rate",
  },
  topup: {
    issuanceVsRedemption: "Issuance vs Redemption Trend",
    channelBreakdown: "Channel Breakdown",
    issued: "Issued",
    redeemed: "Redeemed",
    corporatePortal: "Corporate Portal",
    retailPOS: "Retail POS", 
    online: "Online",
  },
  transactions: {
    title: "Real-time Transaction Feed",
    search: "Search transactions...",
    filter: "Filter",
    cardId: "Card ID",
    balance: "Balance",
    completed: "completed",
    pending: "pending",
    redemption: "redemption",
    topup: "topup",
    partialRedemption: "partial redemption",
    refund: "refund",
    managementTitle: "Transaction Management",
    managementSubtitle: "Monitor and manage all card transactions",
    export: "Export",
    refresh: "Refresh",
    totalTransactions: "Total Transactions",
    successful: "Successful",
    failed: "Failed",
    realTimeFeed: "Real-Time Transaction Feed",
    realTimeFeedDesc: "Live transaction monitoring with advanced filters",
    allStatus: "All Status",
    allTypes: "All Types",
    purchase: "Purchase",
    partialRedemptionTitle: "Partial Redemption",
    partialRedemptionDesc: "Manage partial card redemptions and balances",
    partialRedemptionRules: "Partial Redemption Rules",
    active: "Active",
    minimumBalance: "Minimum balance required",
    allowPartialRedemptions: "Allow partial redemptions",
    yes: "Yes",
    minimumTransactionAmount: "Minimum transaction amount",
    configureRules: "Configure Rules",
    disputeHandling: "Dispute Handling",
    disputeHandlingDesc: "Manage transaction disputes and refunds",
    transaction: "Transaction",
    amount: "Amount",
    reason: "Reason",
    resolved: "resolved",
    investigating: "investigating",
    reversalRefundCenter: "Reversal & Refund Center",
    reversalRefundCenterDesc: "Process transaction reversals and refunds",
    pendingReversals: "Pending Reversals",
    completedRefunds: "Completed Refunds",
    failedReversals: "Failed Reversals",
    process: "Process",
    view: "View",
    retry: "Retry",
  },
  account: {
    title: "Account & Role Management",
    subtitle: "Manage user roles, permissions, and access control",
    addUser: "Add User",
    users: "users",
    permissions: "permissions",
    roleHierarchy: "Role Hierarchy",
    roleHierarchyDesc: "View and manage role permissions structure",
    recentActivity: "Recent Activity",
    recentActivityDesc: "Audit trail of recent system actions",
    ssoIntegration: "SSO Integration",
    ssoIntegrationDesc: "Configure single sign-on providers",
    fullAccess: "Full Access",
    settlementReports: "Settlement, Reports",
    merchantOperations: "Merchant Operations",
    customerSupport: "Customer Support",
    fullSystemAccess: "Full system access",
    configure: "Configure",
    setup: "Setup",
    active: "Active",
    inactive: "Inactive",
    oauth: "OAuth 2.0 integration",
    activeDirectory: "Active Directory sync",
    enterpriseSSO: "Enterprise SSO",
    createdMerchant: "Created merchant account",
    updatedSettlement: "Updated settlement rules",
    deletedCards: "Deleted expired cards",
    minAgo: "min ago",
    hourAgo: "hour ago",
  },
  cardInventory: {
    title: "Card & Inventory Management",
    subtitle: "Manage card issuance, inventory, and lifecycle",
    bulkUpload: "Bulk Upload",
    newBatch: "New Batch",
    totalCardsIssued: "Total Cards Issued",
    activeCards: "Active Cards",
    expiredCards: "Expired Cards",
    pendingActivation: "Pending Activation",
    corporateGeneration: "Corporate Generation",
    corporateGenerationDesc: "Create and manage corporate card batches",
    campaignName: "Campaign Name",
    enterCampaignName: "Enter campaign name",
    batchAmount: "Batch Amount",
    cardValue: "Card Value",
    whitelistUpload: "Whitelist Upload",
    dropCsvFile: "Drop CSV file here or click to browse",
    generateBatch: "Generate Batch",
    recentBatches: "Recent Batches",
    recentBatchesDesc: "Track batch generation progress",
    cards: "cards",
    completed: "completed",
    processing: "processing",
    pending: "pending",
    cardTypeDistribution: "Card Type Distribution",
    cardTypeDistributionDesc: "Overview of card types and their status",
    physicalCards: "Physical Cards",
    eGiftCards: "E-Gift Cards",
    corporateCards: "Corporate Cards",
    total: "total",
    active: "Active",
    expired: "Expired",
    topUpReloadControls: "Top-Up & Reload Controls",
    topUpReloadControlsDesc: "Manage card reloading and top-up settings",
    autoTopUp: "Auto Top-Up",
    autoTopUpDesc: "Automatic balance reload",
    manualReload: "Manual Reload",
    manualReloadDesc: "User-initiated top-ups",
    corporateReload: "Corporate Reload",
    corporateReloadDesc: "Bulk corporate top-ups",
    enabled: "Enabled",
    expiryManagement: "Expiry Management",
    expiryManagementDesc: "Card expiration and recall settings",
    expiringSoon: "Expiring Soon",
    expiredToday: "Expired Today",
    sendExpiryNotifications: "Send Expiry Notifications",
    recallExpiredCards: "Recall Expired Cards",
  },
  merchant: {
    title: "Merchant & Tenant Management",
    subtitle: "Manage merchant onboarding, dashboards, and settlements",
    viewAll: "View All",
    addMerchant: "Add Merchant",
    totalMerchants: "Total Merchants",
    activeMerchants: "Active Merchants",
    pendingApproval: "Pending Approval",
    inactive: "Inactive",
    merchantOnboarding: "Merchant Onboarding",
    merchantOnboardingDesc: "Quick onboarding form for new merchants",
    businessName: "Business Name",
    enterBusinessName: "Enter business name",
    category: "Category",
    foodBeverage: "Food & Beverage",
    contactEmail: "Contact Email",
    businessAddress: "Business Address",
    feeStructure: "Fee Structure",
    transactionPercent: "Transaction %",
    monthlyFee: "Monthly fee",
    submitApplication: "Submit Application",
    pendingApprovals: "Pending Approvals",
    pendingApprovalsDesc: "Merchants awaiting approval",
    complete: "Complete",
    pending: "Pending",
    electronics: "Electronics",
    retail: "Retail",
    submitted: "Submitted",
    review: "Review",
    approve: "Approve",
    topPerformingMerchants: "Top Performing Merchants",
    topPerformingMerchantsDesc: "Merchant performance dashboard and analytics",
    transactions: "transactions",
    revenue: "Revenue",
    growth: "Growth",
    active: "active",
    edit: "Edit",
    feeStructureManagement: "Fee Structure Management",
    feeStructureManagementDesc: "Configure merchant fee structures",
    standardFeeStructure: "Standard Fee Structure",
    transactionFee: "Transaction Fee",
    setupFee: "Setup Fee",
    premiumFeeStructure: "Premium Fee Structure",
    editFeeStructures: "Edit Fee Structures",
    settlementCycles: "Settlement Cycles",
    settlementCyclesDesc: "Manage merchant settlement schedules",
    scheduled: "scheduled",
    processing: "processing",
    amount: "Amount",
    cycle: "Cycle",
    nextSettlement: "Next Settlement",
    daily: "Daily",
    weekly: "Weekly",
    biweekly: "Bi-weekly",
    configureSchedules: "Configure Schedules",
  },
  settlement: {
    title: "Settlement & Reconciliation",
    subtitle: "Manage automated reconciliation and float management",
    exportReport: "Export Report",
    reconcileNow: "Reconcile Now",
    totalFloat: "Total Float",
    pendingSettlements: "Pending Settlements",
    reconciledToday: "Reconciled Today",
    exceptions: "Exceptions",
    automatedReconciliation: "Automated Reconciliation",
    automatedReconciliationDesc: "Real-time reconciliation status for all merchants",
    last: "Last",
    next: "Next",
    completed: "completed",
    running: "running",
    pending: "pending",
    failed: "failed",
    floatManagement: "Float Management",
    floatManagementDesc: "Monitor and manage system float balance",
    currentFloatBalance: "Current Float Balance",
    ofTarget: "of target",
    target: "Target",
    floatMovements: "Float Movements",
    cardIssuance: "Card Issuance",
    merchantSettlement: "Merchant Settlement",
    cardTopUp: "Card Top-up",
    refundProcessing: "Refund Processing",
    settlementFileExport: "Settlement File Export",
    settlementFileExportDesc: "Generate and download settlement reports",
    dailySettlement: "Daily Settlement",
    dailySettlementDesc: "Export daily settlement summary",
    generateReport: "Generate Report",
    lastGenerated: "Last generated",
    monthlyReconciliation: "Monthly Reconciliation",
    monthlyReconciliationDesc: "Monthly reconciliation report",
    exceptionReport: "Exception Report",
    exceptionReportDesc: "Failed reconciliation details",
    hoursAgo: "hours ago",
    dayAgo: "day ago",
    manual: "Manual",
  },
  common: {
    language: "Language",
    thai: "Thai",
    english: "English",
  },
  compliance: {
    title: 'Compliance & Audit',
    subtitle: 'Regulatory compliance, data retention, and audit management',
    complianceScore: 'Compliance Score',
    activePolicies: 'Active Policies',
    pendingReviews: 'Pending Reviews',
    violations: 'Violations',
    exportReport: 'Export Report',
    generateAudit: 'Generate Audit',
    regulatoryReporting: {
      title: 'Regulatory Reporting',
      subtitle: 'Track compliance status and generate regulatory reports',
      lastAudit: 'Last audit',
      nextDue: 'Next due',
      highPriority: 'high priority',
      mediumPriority: 'medium priority',
      compliant: 'compliant',
      pending: 'pending',
      view: 'View'
    },
    dataRetention: {
      title: 'Data Retention Policies',
      subtitle: 'Manage data lifecycle and retention rules',
      autoDelete: 'Auto-delete',
      manual: 'Manual',
      retentionPeriod: 'Retention Period',
      lastCleanup: 'Last Cleanup',
      configurePolicies: 'Configure Policies',
      transactionRecords: 'Transaction Records',
      customerData: 'Customer Data',
      auditLogs: 'Audit Logs',
      financialReports: 'Financial Reports',
      years: 'years'
    },
    consentManagement: {
      title: 'Consent Management',
      subtitle: 'Track and manage user consent preferences',
      total: 'total',
      consented: 'Consented',
      declined: 'Declined',
      pending: 'Pending',
      manageConsent: 'Manage Consent',
      marketingCommunications: 'Marketing Communications',
      dataProcessing: 'Data Processing',
      thirdPartySharing: 'Third-party Sharing'
    },
    auditTrail: {
      title: 'Audit Trail',
      subtitle: 'Comprehensive audit log and activity tracking',
      systemEventsToday: 'System Events Today',
      auditCoverage: 'Audit Coverage',
      securityAlerts: 'Security Alerts',
      viewFullAuditLog: 'View Full Audit Log',
      exportAuditReport: 'Export Audit Report'
    }
  },
  security: {
    title: 'Security & Compliance',
    subtitle: 'Manage user access, audit trails, fraud detection, and compliance tools',
    fraudDetectionRate: 'Fraud Detection Rate',
    blockedTransactions: 'Blocked Transactions',
    mfaCoverage: 'MFA Coverage',
    securityAlerts: 'Security Alerts',
    viewLogs: 'View Logs',
    configureRules: 'Configure Rules',
    userAccessControl: 'User Access Control',
    auditTrail: 'Audit Trail',
    amlReporting: 'AML Reporting',
    pdpaCompliance: 'PDPA Compliance',
    userManagement: {
      title: 'User Management',
      subtitle: 'Create and manage user accounts with role-based permissions',
      addUser: 'Add User',
      exportUsers: 'Export Users',
      viewAllUsers: 'View All Users',
      active: 'Active',
      inactive: 'Inactive'
    },
    rolePermissions: {
      title: 'Role-Based Permissions',
      subtitle: 'Manage roles and permission templates',
      createRole: 'Create Role',
      permissionMatrix: 'Permission Matrix',
      systemAdmin: 'System Admin',
      financeManager: 'Finance Manager',
      supportAgent: 'Support Agent',
      merchantManager: 'Merchant Manager',
      fullAccess: 'Full Access',
      financialOperations: 'Financial Operations',
      customerSupport: 'Customer Support',
      tenantManagement: 'Tenant Management',
      completeSystemAccess: 'Complete system access',
      settlementReconciliation: 'Settlement & reconciliation',
      cardInquiryAssistance: 'Card inquiry & assistance',
      merchantOperations: 'Merchant operations',
      users: 'users'
    },
    authentication: {
      title: 'Authentication Settings',
      subtitle: 'Multi-factor authentication and SSO configuration',
      multiFactorAuth: 'Multi-Factor Authentication',
      smsAuth: 'SMS Authentication',
      emailVerification: 'Email Verification',
      authenticatorApp: 'Authenticator App',
      hardwareToken: 'Hardware Token',
      textMessageVerification: 'Text message verification',
      emailBasedAuth: 'Email-based authentication',
      totpAppVerification: 'TOTP app verification',
      physicalSecurityKeys: 'Physical security keys',
      ssoIntegration: 'SSO Integration',
      googleSSO: 'Google SSO',
      microsoftSSO: 'Microsoft SSO',
      gmailAuth: 'Gmail authentication',
      azureAdIntegration: 'Azure AD integration'
    },
    activityLogging: {
      title: 'Activity Logging',
      subtitle: 'Real-time audit trail of all system activities',
      search: 'Search',
      filter: 'Filter',
      export: 'Export',
      timestamp: 'Timestamp',
      user: 'User',
      action: 'Action',
      module: 'Module'
    },
    logManagement: {
      title: 'Log Management',
      subtitle: 'Configure log retention and archival',
      retentionPeriod: 'Log Retention Period',
      autoArchival: 'Auto Archival',
      days90: '90 days',
      days180: '180 days',
      year1: '1 year',
      years3: '3 years',
      enabled: 'Enabled',
      disabled: 'Disabled'
    }
  },
  integration: {
    title: 'Integration & API Management',
    subtitle: 'Manage API endpoints, webhooks, and external integrations',
    totalApiCalls: 'Total API Calls',
    successRate: 'Success Rate',
    avgResponseTime: 'Avg Response Time',
    rateLimitHits: 'Rate Limit Hits',
    viewDocs: 'View Docs',
    apiConsole: 'API Console',
    apiCatalogSandbox: {
      title: 'API Catalog & Sandbox',
      subtitle: 'Manage API endpoints and test in sandbox environment',
      cardIssuance: 'Card Issuance',
      transactionProcessing: 'Transaction Processing',
      balanceInquiry: 'Balance Inquiry',
      merchantVerification: 'Merchant Verification',
      uptime: 'uptime',
      calls: 'calls',
      rateLimit: 'Rate limit',
      test: 'Test',
      openSandbox: 'Open Sandbox'
    },
    apiStatusDashboard: {
      title: 'API Status Dashboard',
      subtitle: 'Monitor external system integrations',
      crmSystem: 'CRM System',
      paymentGateway: 'Payment Gateway',
      merchantDirectory: 'Merchant Directory',
      notificationService: 'Notification Service',
      active: 'active',
      inactive: 'inactive',
      lastHeartbeat: 'Last heartbeat',
      errorRate: 'Error rate',
      retryCount: 'Retry count',
      minAgo: 'min ago',
      secAgo: 'sec ago'
    },
    webhookManagement: {
      title: 'Webhook Management',
      subtitle: 'Configure and manage webhook endpoints',
      transactionCompleted: 'Transaction Completed',
      cardIssued: 'Card Issued',
      balanceUpdated: 'Balance Updated',
      merchantOnboarded: 'Merchant Onboarded',
      lastTrigger: 'Last trigger',
      edit: 'Edit',
      addWebhook: 'Add Webhook',
      hourAgo: 'hour ago',
      dayAgo: 'day ago'
    },
    rateLimiting: {
      title: 'Rate Limiting',
      subtitle: 'Configure API rate limits and quotas',
      currentUsage: 'Current Usage',
      apiCallsPerMinute: 'API Calls (per minute)',
      concurrentConnections: 'Concurrent Connections',
      webhookDeliveries: 'Webhook Deliveries',
      rateLimitConfig: 'Rate Limit Configuration',
      requestsPerMinute: 'Requests per minute',
      burstLimit: 'Burst limit',
      updateLimits: 'Update Limits'
    }
  }
};

type Language = 'th' | 'en';
type Translations = typeof thTranslations;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('th');

  const translations = {
    th: thTranslations,
    en: enTranslations,
  };

  const value = {
    language,
    setLanguage,
    t: translations[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // Provide a fallback instead of throwing
    console.warn('useLanguage called outside of LanguageProvider, using fallback');
    return {
      language: 'th' as Language,
      setLanguage: () => {},
      t: thTranslations,
    };
  }
  return context;
}